- hosts: localhost
  vars_files:
          - login.yml
  tasks:
          - name: To launch ec2-instance
             ec2:
                key_name: mykey
                instance_type: t2.micro
                image: ami-0bcf5425cdc1d8a85
                wait: true
                group: default
                count: 1
                vpc_subnet_id: subnet-0ea0dded0d5d89dc6
                assign_public_ip: yes
                region: ap-south-1
                state: present
                aws_access_key: "{{ access_key }}"
                aws_secret_key: "{{ secret_key }}"
                instance_tags:
                  Name: webserver
                register: ec2
                wait: yes
