- hosts: localhost
  vars_files:
          - login.yml
  tasks:
          - name: To launch ec2-instance
             ec2:
                key_name: mykey
                instance_type: t2.micro
                image: ami-0bcf5425cdc1d8a85
                wait: true
                group: default
                count: 1
                vpc_subnet_id: subnet-0ea0dded0d5d89dc6
                assign_public_ip: yes
                region: ap-south-1
                state: present
                aws_access_key: "{{ access_key }}"
                aws_secret_key: "{{ secret_key }}"
                instance_tags:
                  Name: webserver
                register: ec2
                wait: yes
                
- hosts: "{{ groups.tag_Name_Myweb1 }}"
  tasks:
          - name: copy the docker repo file
            copy:
                  src: "docker.repo"
                  dest: "/etc/yum.repos.d/"

          - name: yum repolist
            command: yum repolist
            args:
                    warn: no

          - name: start the docker service
            service:
                    name: docker
                    state: started

          - name: install docker-py
            pip:
                    name: docker-py

          - name: Pull docker image from docker hub
            docker_image:
                    name: manisha001agrawal/httpd:v1
                    pull: True
            ignore_errors: yes

          - name: Launch docker conatainer
            docker_container:
                    name: myos1
                    image: manisha001agrawal/httpd:v1
            register: y
