- hosts: localhost
  vars_files:
          - login.yml
  tasks:
          - name: To launch ec2-instance
            ec2_instance:
                    region: ap-south-1
                    key_name: "mykey"
                    name: Os_from_ansible
                    state: present
                    vpc_subnet_id: subnet-0ea0dded0d5d89dc6
                    instance_type: t2.micro
                    security_group: default
                    network:
                      assign_public_ip: true
                    image_id: ami-0a9d27a9f4f5c0efc
                    aws_access_key: "{{access_key}}"
                    aws_secret_key: "{{secret_key}}"
                    tags:
                      Name: "Myweb1"
                    wait: yes
          - meta: refresh_inventory
- hosts: "{{ groups.tag_Name_Myweb1 }}"
  tasks:
          - name: copy the docker repo file
            copy:
                  src: "docker.repo"
                  dest: "/etc/yum.repos.d/"

          - name: yum repolist
            command: yum repolist
            args:
                    warn: no

          - name: start the docker service
            service:
                    name: docker
                    state: started

          - name: install docker-py
            pip:
                    name: docker-py

          - name: Pull docker image from docker hub
            docker_image:
                    name: manisha001agrawal/httpd:v1
                    pull: True
            ignore_errors: yes

          - name: Launch docker conatainer
            docker_container:
                    name: myos1
                    image: manisha001agrawal/httpd:v1
            register: y
